### ISSUE TITLE
NullPointerException in ParametersManager

### ISSUE THREAD

**Issue by sczerwinski** [GlimpseFramework/glimpse-framework#2]
If there is a problem with finding a proper converter, `NullPointerException` is thrown at `ParametersManager.findConverter()`.

```java
private ParameterConverter<?> findConverter(Object rawValue) {
	ParameterConverter<?> converter = null;
	for (Class<?> cls = rawValue.getClass(); converter == null; cls = cls.getSuperclass()) { // <-- NullPointerException
		converter = converters.get(cls);
	}
	return converter;
}
```

An exception indicating a real cause should be thrown instead.

**Comment by sczerwinski** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at org.glimpseframework.internal.shader.parameters.ParametersManager.findConverter(ParametersManager.java:78)
	at org.glimpseframework.internal.shader.parameters.ParametersManager.applyParameter(ParametersManager.java:72)
	at org.glimpseframework.internal.shader.parameters.ParametersManager.applyParameters(ParametersManager.java:66)
	at org.glimpseframework.api.Scene.renderModel(Scene.java:114)
	at org.glimpseframework.api.Scene.doRender(Scene.java:101)
	at org.glimpseframework.api.Scene.render(Scene.java:88)
	at org.glimpseframework.android.AndroidScene.onDrawFrame(AndroidScene.java:58)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by sczerwinski** [comment]
`null` parameter is now handled by `NullConverter`
