### ISSUE TITLE
glimpse.io.ResourceNotFoundException

### ISSUE THREAD

**Issue by changjiashuai** [GlimpseFramework/glimpse-framework#59]
I have found a *bug* in Glimpse Framework.

### How to reproduce the issue
just run GlimpsePreview in mac osx.

### Details
 com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at com.jogamp.opengl.util.AWTAnimatorImpl$1.run(AWTAnimatorImpl.java:170)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: glimpse.io.ResourceNotFoundException: glimpse.materials.Plastic_vertex.glsl
	at glimpse.io.Resource.getInputStream(Resource.kt:16)
	at glimpse.io.Resource$lines$2.invoke(Resource.kt:21)
	at glimpse.io.Resource$lines$2.invoke(Resource.kt:11)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at glimpse.io.Resource.getLines(Resource.kt)
	at glimpse.materials.PlasticShaderHelper$program$2$1$1.invoke(Plastic.kt:45)
	at glimpse.materials.PlasticShaderHelper$program$2$1$1.invoke(Plastic.kt:40)
	at glimpse.shaders.ProgramBuilder.invoke(ProgramBuilder.kt:17)
	at glimpse.shaders.ProgramBuilder.vertexShader(ProgramBuilder.kt:30)
	at glimpse.materials.PlasticShaderHelper$program$2$1.invoke(Plastic.kt:44)
	at glimpse.materials.PlasticShaderHelper$program$2$1.invoke(Plastic.kt:40)
	at glimpse.shaders.ProgramBuilderKt.shaderProgram(ProgramBuilder.kt:60)
	at glimpse.materials.PlasticShaderHelper$program$2.invoke(Plastic.kt:43)
	at glimpse.materials.PlasticShaderHelper$program$2.invoke(Plastic.kt:40)
	at glimpse.gles.delegates.DisposableLazyDelegate.getValue(DisposableLazyDelegate.kt:22)
	at glimpse.materials.PlasticShaderHelper.getProgram(Plastic.kt)
	at glimpse.materials.ShaderHelper.use(ShaderHelper.kt:61)
	at glimpse.materials.Plastic.render(Plastic.kt:25)
	at glimpse.preview.GlimpsePreviewKt$main$2$4.invoke(GlimpsePreview.kt:216)
	at glimpse.preview.GlimpsePreviewKt$main$2$4.invoke(GlimpsePreview.kt)
	at glimpse.jogl.GlimpseFrame$EventListener.display(GlimpseFrame.kt:109)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLJPanel$Updater.display(GLJPanel.java:1446)
	at com.jogamp.opengl.awt.GLJPanel$10.run(GLJPanel.java:1521)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 31 more
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:98)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught ResourceNotFoundException: glimpse.materials.Plastic_vertex.glsl on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at com.jogamp.opengl.util.AWTAnimatorImpl$1.run(AWTAnimatorImpl.java:170)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by sczerwinski** [comment]
Hi @changjiashuai 

Thanks for your feedback.

I'm trying to reproduce the problem on Mac.
Are you starting the preview app with this command?
```
./gradlew run
```

**Comment by sczerwinski** [comment]
Updated [README.md](https://github.com/GlimpseFramework/glimpse-framework/blob/master/README.md) to include instructions on running the Preview application:

> To run Glimpse Framework Preview application, execute the command:
> ```
> ./gradlew clean build run
> ```
>
> Some of the resources used by the application are generated by Gradle scripts, so the application will not work properly when started from an IDE.

**Comment by sczerwinski** [comment]
Tested on macOS Sierra 10.12.5
